USE mydatabase;

CREATE TABLE IF NOT EXISTS my_table (
    player_id INT,
    player_name VARCHAR(255),
    transfers_date DATE,
    transfer_fee DECIMAL(20,2),
    transfers_teams_in_id INT,
    transfers_teams_in_name VARCHAR(255),
    transfers_teams_out_id INT,
    transfers_teams_out_name VARCHAR(255),
    season_of_transfer INT,
    transfers_window VARCHAR(255),
    player_firstname VARCHAR(255),
    player_lastname VARCHAR(255),
    player_age INT,
    player_birth_date DATE,
    player_birth_place VARCHAR(255),
    player_birth_country VARCHAR(255),
    player_nationality VARCHAR(255),
    player_height DECIMAL(5,2),
    player_weight DECIMAL(5,2),
    player_injured BOOLEAN,
    player_photo VARCHAR(255),
    statistics_team_id INT,
    statistics_team_name VARCHAR(255),
    statistics_team_logo VARCHAR(255),
    statistics_league_id INT,
    statistics_league_name VARCHAR(255),
    statistics_league_country VARCHAR(255),
    statistics_league_logo VARCHAR(255),
    statistics_league_flag VARCHAR(255),
    statistics_league_season VARCHAR(255),
    statistics_games_appearences INT,
    statistics_games_lineups INT,
    statistics_games_minutes INT,
    statistics_games_number INT,
    statistics_games_position VARCHAR(255),
    statistics_games_rating DECIMAL(5,2),
    statistics_games_captain BOOLEAN,
    statistics_substitutes_in INT,
    statistics_substitutes_out INT,
    statistics_substitutes_bench INT,
    statistics_shots_total INT,
    statistics_shots_on INT,
    statistics_goals_total INT,
    statistics_goals_conceded INT,
    statistics_goals_assists INT,
    statistics_goals_saves INT,
    statistics_passes_total INT,
    statistics_passes_key INT,
    statistics_passes_accuracy DECIMAL(5,2),
    statistics_tackles_total INT,
    statistics_tackles_blocks INT,
    statistics_tackles_interceptions INT,
    statistics_duels_total INT,
    statistics_duels_won INT,
    statistics_dribbles_attempts INT,
    statistics_dribbles_success INT,
    statistics_dribbles_past INT,
    statistics_fouls_drawn INT,
    statistics_fouls_committed INT,
    statistics_cards_yellow INT,
    statistics_cards_yellowred INT,
    statistics_cards_red INT,
    statistics_penalty_won INT,
    statistics_penalty_commited INT,
    statistics_penalty_scored INT,
    statistics_penalty_missed INT,
    statistics_penalty_saved INT,
    performance_metric DECIMAL(10,2),
    transfer_type VARCHAR(255)
);


LOAD DATA INFILE '/var/lib/mysql-files/merged_data_241004.csv'
INTO TABLE my_table
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(player_id,player_name,transfers_date,transfer_fee,transfers_teams_in_id,transfers_teams_in_name,transfers_teams_out_id,transfers_teams_out_name,season_of_transfer,transfers_window,player_firstname,player_lastname,player_age,player_birth_date,player_birth_place,player_birth_country,player_nationality,player_height,player_weight,player_injured,player_photo,statistics_team_id,statistics_team_name,statistics_team_logo,statistics_league_id,statistics_league_name,statistics_league_country,statistics_league_logo,statistics_league_flag,statistics_league_season,statistics_games_appearences,statistics_games_lineups,statistics_games_minutes,statistics_games_number,statistics_games_position,statistics_games_rating,statistics_games_captain,statistics_substitutes_in,statistics_substitutes_out,statistics_substitutes_bench,statistics_shots_total,statistics_shots_on,statistics_goals_total,statistics_goals_conceded,statistics_goals_assists,statistics_goals_saves,statistics_passes_total,statistics_passes_key,statistics_passes_accuracy,statistics_tackles_total,statistics_tackles_blocks,statistics_tackles_interceptions,statistics_duels_total,statistics_duels_won,statistics_dribbles_attempts,statistics_dribbles_success,statistics_dribbles_past,statistics_fouls_drawn,statistics_fouls_committed,statistics_cards_yellow,statistics_cards_yellowred,statistics_cards_red,statistics_penalty_won,statistics_penalty_commited,statistics_penalty_scored,statistics_penalty_missed,statistics_penalty_saved,performance_metric,transfer_type);