version: '3.8'

services:
  app:
    image: adrianmadry968/la_liga_transfers-app:latest
    ports:
      - "8501:8501"
    depends_on:
      - database
    volumes:
      - ./app:/app


  database:
    image: adrianmadry968/la_liga_transfers-database:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
